# Generated by Django 5.0.6 on 2025-04-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNum', models.CharField(max_length=15, unique=True)),
                ('reg_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
