# Generated by Django 5.0.6 on 2025-02-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登録日時'),
        ),
    ]
