# Generated by Django 5.0.6 on 2025-01-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('max_uses', models.PositiveIntegerField(default=100)),
                ('probability', models.FloatField(default=0.33)),
            ],
        ),
    ]
