# Generated by Django 5.0.6 on 2025-02-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponAPI', '0002_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='description',
            field=models.CharField(choices=[('20代', '20代'), ('30代', '30代'), ('40代', '40代'), ('50代', '50代'), ('60代', '60代'), ('60代以上', '60代以上')], default='20代', max_length=20),
        ),
    ]
