# Generated by Django 5.0.6 on 2025-02-06 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couponAPI', '0003_alter_questionnaire_description'),
        ('userManager', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='description',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='questions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CouponLotteryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_time', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponAPI.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManager.user')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responses', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='couponAPI.questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userManager.user')),
            ],
        ),
    ]
